---
# tasks file for docker-role
- name: Load a variable file based on the OS type.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- name: pre-requisites tasks
  import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: ensure services running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ docker.services }}"
